# -*- YAML -*-
# Copyright (C) 2011 Urabe, Shyouhei.  All rights reserved.
#
# This file is  a part of the programming language  Ruby.  Permission is hereby
# granted,  to either  redistribute  or  modify this  file,  provided that  the
# conditions  mentioned in  the file  COPYING are  met.  Consult  the  file for
# details.

# When you see Travis CI issues, or you are interested in understanding how to
# manage, please check the link below.
# https://github.com/ruby/ruby/wiki/CI-Servers#travis-ci

# We enable Travis on the specific branches or forked repositories here.
if: >-
  (repo != ruby/ruby OR branch = master OR branch =~ /^ruby_\d_\d$/)
  AND (commit_message !~ /\[DOC\]/)

language: c

os: linux

dist: jammy

git:
  quiet: true

matrix:
  include:
    - arch: arm64
    - arch: ppc64le
    - arch: s390x
  fast_finish: true

script:
  - false

# We want to be notified when something happens.
notifications:
  email:
    recipients:
      - jaruga@ruby-lang.org
      - nobu@ruby-lang.org
      - hsbt@ruby-lang.org
    on_success: never
    on_failure: always
